### ISSUE TITLE
Lua errors

### ISSUE THREAD

**Issue by Aka7tsu4** [ChubbyGuy/Justice-System-DarkRp-#1]
[ERROR] addons/justicesystem/lua/autorun/server/main.lua:567: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
2. func - addons/justicesystem/lua/autorun/server/main.lua:567
3. unknown - lua/includes/extensions/net.lua:32

**Comment by ChubbyGuy** [comment]
Can you give me more information?

What exactly triggered this? Can you retrigger it?

**Comment by Aka7tsu4** [comment]
[ERROR] addons/justicesystem/lua/autorun/server/main.lua:568: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
2. func - addons/justicesystem/lua/autorun/server/main.lua:568
3. unknown - lua/includes/extensions/net.lua:32

**Comment by Aka7tsu4** [comment]
[ERROR] addons/justicesystem/lua/autorun/server/main.lua:198: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
2. getCrimes - addons/justicesystem/lua/autorun/server/main.lua:198
3. func - addons/justicesystem/lua/autorun/server/main.lua:710
4. unknown - lua/includes/extensions/net.lua:32

**Comment by ChubbyGuy** [comment]
From what I can tell, you somehow messed up the nets, or another addon is conflicting because of netmessege names.

**Comment by ChubbyGuy** [comment]
Don't just post your error btw, otherwise, I'll just close the thread. Tell me what you were doing, and if it happens if you redo it.
